edit_uri: ""
markdown_extensions:
  - admonition
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tasklist:
      clickable_checkbox: false
      custom_checkbox: true
  - toc:
      permalink: true
      toc_depth: 3
nav:
  - "index.md"
repo_name: br3ndonland/whylogs-v1
repo_url: https://github.com/br3ndonland/whylogs-v1
site_name: whylogs-v1 docs
site_url: ""
theme:
  favicon: assets/images/favicon.png
  features:
    - header.autohide
    - navigation.instant
    - navigation.top
  font: false
  icon:
    logo: octicons/book-24
    repo: octicons/mark-github-16
  name: material
  palette:
    - media: "(prefers-color-scheme: dark)"
      accent: cyan
      primary: cyan
      scheme: slate
      toggle:
        icon: material/weather-night
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      accent: cyan
      primary: cyan
      scheme: default
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
use_directory_urls: false
