name: whylogs Java CI
on:
  push:
    branches: [ mainline, release]
  pull_request:
    branches: [ mainline, release]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest]
        scala-version: [2.11, 2.12]
        spark-version: [2.4.7, 3.1.1]
        exclude:
          - scala-version: 2.11
            spark-version: 3.1.1
        include:
          - scala-verison: 2.13
            spark-version: 3.2.0
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash
        working-directory: java
    steps:
      - uses: actions/checkout@v2
      - name: Change to Java dir
        run: |
          echo $(pwd)
      - name: Setup Java 8
        uses: actions/setup-java@v1
        with:
          java-version: 8
      - name: Cache Gradle dependencies
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - uses: eskatos/gradle-command-action@v1
        with:
          build-root-directory: java
          arguments: build
        env:
          SCALA_VERSION : ${{ matrix.scala-version }}
          SPARK_VERSION : ${{ matrix.spark-version }}
      - name: Smoke test jar in client environment
        uses: gradle/gradle-build-action@v2
        with:
          build-root-directory: java/smoketest
          arguments: run
          gradle-executable: java/gradlew
